-- ---------------------------------------------------------------------------
-- V12 — a bill's payments become rows
--
-- An order carried one payment_method, one amount_tendered and one
-- change_amount. That shape says a bill is settled exactly once by exactly one
-- method, and three things this system already needs are impossible inside it:
--
--   * splitting a bill across cash and card, which SCREENS §2.1 wants and
--     which every till on the street does,
--   * a KHQR code that was shown and never paid — the columns could only
--     describe money that arrived, so an abandoned code left no trace,
--   * a refund, which P7 has to write against the payment it reverses.
--
-- docs/PLAN.md numbered this V9. V9, V10 and V11 were taken by smaller changes
-- that shipped first; the number moved, the work did not.
--
-- ---------------------------------------------------------------------------
-- Expand now, contract later
--
-- PLAN.md said to drop the three columns here, once every paid order had its
-- row. This writes the rows and leaves the columns alone.
--
-- Dropping them in the same migration that introduces their replacement makes
-- the deploy one-way: the moment it runs, the previous build of the
-- application — which reads orders.payment_method — can no longer start, so a
-- bad release has no way back. Nothing is gained by it either, because what
-- makes two sources of truth dangerous is two readers, and after this
-- migration the entity no longer maps those columns at all. They are frozen
-- history that nothing reads.
--
-- The contract step is V13, written alongside this one and deliberately not
-- applied with it: it is the irreversible half, and it should run against a
-- database whose sale_payment rows someone has looked at.
--
-- Back up before running this.
-- ---------------------------------------------------------------------------

CREATE TABLE sale_payment (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT         NOT NULL,
    method        VARCHAR(20)    NOT NULL,
    amount        NUMERIC(12, 2) NOT NULL,
    amount_khr    NUMERIC(14, 0),

    -- Cash only. Nobody hands over a card and nobody gets change from a QR, so
    -- on every other method these stay null rather than repeating the amount
    -- and reading as though something had been counted out.
    tendered      NUMERIC(12, 2),
    change_amount NUMERIC(12, 2),

    -- The bank's reference for a KHQR payment, or whatever the cashier was
    -- given for a transfer. The one field that makes a line reconcilable
    -- against a bank statement.
    reference     VARCHAR(100),

    -- How Bakong identifies the transaction. orders.khqr_md5 holds the *live*
    -- code's identifier so a refreshed till redraws the same QR; this one
    -- belongs to the money that actually arrived. They are the same string for
    -- a code that was paid, and only this one survives a second attempt.
    khqr_md5      VARCHAR(32),

    status        VARCHAR(20)    NOT NULL DEFAULT 'CAPTURED',
    created_at    TIMESTAMP      NOT NULL,

    CONSTRAINT fk_payment_order  FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_payment_method CHECK (method IN ('CASH', 'CARD', 'KHQR', 'TRANSFER')),
    CONSTRAINT ck_payment_status CHECK (status IN (
        'PENDING',    -- a code is on screen; no money yet
        'CAPTURED',   -- the money arrived
        'FAILED',     -- the attempt ended without money
        'REFUNDED')), -- reversed by a return (P7)
    CONSTRAINT ck_payment_amount CHECK (amount >= 0)
);

CREATE INDEX ix_payment_order ON sale_payment (order_id);
CREATE INDEX ix_payment_md5   ON sale_payment (khqr_md5);

-- ---------------------------------------------------------------------------
-- Every settled bill gets its payment
--
-- paid_at is when the money arrived. Where an old row never recorded one, the
-- audit timestamps are the closest thing to it that was actually written down;
-- a timestamp invented here would be indistinguishable from a recorded one.
-- ---------------------------------------------------------------------------

INSERT INTO sale_payment
    (order_id, method, amount, amount_khr, tendered, change_amount, reference,
     khqr_md5, status, created_at)
SELECT o.id,
       o.payment_method,
       o.total,
       o.total_khr,
       CASE WHEN o.payment_method = 'CASH' THEN o.amount_tendered END,
       CASE WHEN o.payment_method = 'CASH' THEN o.change_amount END,
       o.khqr_reference,
       o.khqr_md5,
       'CAPTURED',
       COALESCE(o.paid_at, o.mod_dtm, o.reg_dtm, CURRENT_TIMESTAMP)
FROM   orders o
WHERE  o.status = 'PAID'
  AND  o.payment_method IS NOT NULL;

-- ---------------------------------------------------------------------------
-- The assertion
--
-- A bill marked PAID whose method was never recorded would be skipped by the
-- insert above, and its money would quietly disappear from every payment
-- report. This writes such a row with a null method, which the NOT NULL
-- refuses: the migration stops and names the column rather than finishing with
-- a hole in it.
--
-- Where no such order exists it selects nothing and does nothing — which is
-- the case on the database this was written against, where all 192 paid orders
-- carry a method.
-- ---------------------------------------------------------------------------

INSERT INTO sale_payment (order_id, method, amount, status, created_at)
SELECT o.id, NULL, o.total, 'CAPTURED', CURRENT_TIMESTAMP
FROM   orders o
WHERE  o.status = 'PAID'
  AND  NOT EXISTS (SELECT 1 FROM sale_payment p WHERE p.order_id = o.id);
