-- ---------------------------------------------------------------------------
-- V13 — the rate and the cost stop being today's numbers
--
-- Two figures on a settled bill were being read from live settings long after
-- the bill was settled, so both changed retroactively:
--
--   * the exchange rate. orders.total_khr was stamped, but the rate behind it
--     was not, so "what did we convert this at" could only be divided out, and
--     a corrected rate made last month's riel column disagree with the slips
--     customers are holding.
--
--   * the cost of a line. The margin report multiplies historical quantities
--     by product.cost *as it is now* and inner-joins the product, so repricing
--     an ingredient rewrites last year's profit and deleting a product erases
--     its sales from the cost side while leaving them in revenue.
--
-- docs/PLAN.md numbered this V10; V10 and V11 went to other work first.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 1. The rate, dated
--
-- The table is the history and orders.fx_rate_khr is the stamp. Both, because
-- a rate corrected retroactively must not rewrite a receipt somebody already
-- has (ERD §3.9).
-- ---------------------------------------------------------------------------

CREATE TABLE fx_rate (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency   VARCHAR(3)     NOT NULL,
    rate       NUMERIC(14, 4) NOT NULL,
    valid_from DATE           NOT NULL,
    created_by VARCHAR(50),
    created_at TIMESTAMP      NOT NULL,
    CONSTRAINT uk_fx      UNIQUE (currency, valid_from),
    CONSTRAINT ck_fx_rate CHECK (rate > 0)
);

-- Today's rate becomes the first row, the way V11 gave every product an
-- opening balance: the history starts now rather than inventing a past.
--
-- The cast is deliberate. A rate that is not a number stops this migration and
-- names the setting, which is better than a till quietly converting at a
-- figure nobody chose.
INSERT INTO fx_rate (currency, rate, valid_from, created_by, created_at)
SELECT 'KHR', CAST(setting_value AS NUMERIC(14, 4)), CURRENT_DATE, 'system', CURRENT_TIMESTAMP
FROM   app_setting
WHERE  setting_key = 'currency.khrRate'
  AND  setting_value IS NOT NULL;

ALTER TABLE orders ADD COLUMN fx_rate_khr NUMERIC(14, 4);

-- ---------------------------------------------------------------------------
-- Backfilling the stamp is recovery, not guesswork
--
-- total_khr was computed as total x rate and both were stored, so the rate is
-- recoverable by division: it is the number that was actually used, not an
-- assumption about which rate was in force. Bills with no total have no rate
-- to recover and keep null.
-- ---------------------------------------------------------------------------

UPDATE orders
SET    fx_rate_khr = ROUND(total_khr / total, 4)
WHERE  total > 0
  AND  total_khr > 0;

-- ---------------------------------------------------------------------------
-- 2. The cost of a line, stamped like its price
--
-- unit_price has always been copied onto the line at the moment of ordering.
-- unit_cost never was, which is the whole bug: a line remembered what it sold
-- for and not what it cost.
-- ---------------------------------------------------------------------------

ALTER TABLE order_item ADD COLUMN unit_cost      NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE order_item ADD COLUMN cost_estimated BOOLEAN        NOT NULL DEFAULT FALSE;

-- ---------------------------------------------------------------------------
-- And the backfill is a guess, which is why it says so
--
-- Every existing line gets today's product cost. For anything sold before
-- today that is wrong by however much the cost has moved since, and there is
-- no way to do better: a cost that was never recorded cannot be recovered.
--
-- So the lines are flagged. The reports read the flag and label those margins
-- estimated rather than presenting them as measured. A silently plausible
-- wrong number is worse than a labelled gap, and this project has been bitten
-- by a silent substitution before.
--
-- A line whose product has since been deleted gets zero and the same flag:
-- there is nothing left to copy from, and zero cost declares itself as absurd
-- in a way an invented figure would not.
-- ---------------------------------------------------------------------------

UPDATE order_item SET cost_estimated = TRUE;

UPDATE order_item
SET    unit_cost = COALESCE(
           (SELECT p.cost FROM product p WHERE p.id = order_item.product_id), 0);

CREATE INDEX ix_order_item_estimated ON order_item (cost_estimated);
