-- ---------------------------------------------------------------------------
-- V14 — the drawer gets a session
--
-- Cash has been leaving and entering a till that nobody opens or closes. There
-- is no record of what was in the drawer at the start of a day, what should be
-- in it now, or who was standing there — so "we are forty dollars short" has
-- never been a question this system could be asked.
--
-- A shift is that session: opened with a counted float, closed with a counted
-- drawer, and everything that moved cash in between on the record against it.
--
-- docs/PLAN.md numbered this V8. The number went to account lockout.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- One open shift per cashier, enforced by the database
--
-- ERD §3.2 specifies a partial unique index:
--
--     CREATE UNIQUE INDEX ux_shift_one_open
--         ON cash_shift (branch_id, user_ref) WHERE status = 'OPEN';
--
-- and says plainly what it costs: partial indexes are PostgreSQL-only. H2
-- rejects the WHERE, so the test suite would fail at Flyway before a single
-- test ran. PLAN.md P0a deferred the decision to here, on the grounds that by
-- now it would be known whether Docker was available for a Testcontainers
-- suite. It is not: there is no Docker on this machine, so moving the default
-- test task to real PostgreSQL would leave the suite unrunnable locally.
--
-- The remaining options were a vendor-split migration — one index for
-- PostgreSQL, another for H2 — or this. The split was rejected because it
-- makes the constraint that matters most the one thing the local suite does
-- not exercise, and because two schemas drifting is how this project has
-- already been bitten twice.
--
-- So: open_user_ref carries the cashier's id while the shift is open and NULL
-- once it closes. Both engines allow many NULLs in a unique index and neither
-- allows two equal values, which is exactly the partial index's behaviour
-- expressed in one portable column. The same constraint is now exercised by
-- `./gradlew test` on H2 and by the CI postgres job on the real thing.
--
-- A column that repeats a fact can drift from it, which is the objection
-- §1.3 raises against stored running totals. Here it cannot: ck_shift_open_key
-- ties the key, the status and closed_at together, so a row that disagrees
-- with itself is refused rather than merely unlikely.
-- ---------------------------------------------------------------------------

CREATE TABLE cash_shift (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_ref      BIGINT         NOT NULL,

    -- The cashier's id while this shift is open, NULL once it is closed.
    -- Not a convenience: it is the one-open-shift rule.
    open_user_ref BIGINT,

    opened_at     TIMESTAMP      NOT NULL,
    closed_at     TIMESTAMP,

    -- What was counted into the drawer at the start.
    opening_float NUMERIC(12, 2) NOT NULL,

    -- All three are written at close and never before. expected_cash is
    -- opening_float plus every movement, which is derivable at any moment and
    -- therefore has no business being stored mid-shift (ERD §1.3).
    declared_cash NUMERIC(12, 2),
    expected_cash NUMERIC(12, 2),
    variance      NUMERIC(12, 2),

    note          VARCHAR(500),
    status        VARCHAR(20)    NOT NULL DEFAULT 'OPEN',

    act_yn        VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id        VARCHAR(50),
    reg_dtm       TIMESTAMP,
    mod_id        VARCHAR(50),
    mod_dtm       TIMESTAMP,

    CONSTRAINT fk_shift_user     FOREIGN KEY (user_ref) REFERENCES users_infm (id),
    CONSTRAINT uk_shift_one_open UNIQUE (open_user_ref),
    CONSTRAINT ck_shift_status   CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_shift_float    CHECK (opening_float >= 0),

    -- An open shift is open for somebody and has not been closed; a closed one
    -- has been counted. Without this the key could name a different cashier
    -- than user_ref, or linger after closing and lock that cashier out for
    -- good.
    CONSTRAINT ck_shift_open_key CHECK (
        (status = 'OPEN'
            AND open_user_ref = user_ref
            AND closed_at IS NULL
            AND declared_cash IS NULL)
     OR (status = 'CLOSED'
            AND open_user_ref IS NULL
            AND closed_at IS NOT NULL
            AND declared_cash IS NOT NULL))
);

CREATE INDEX ix_shift_user ON cash_shift (user_ref, opened_at);

-- ---------------------------------------------------------------------------
-- Everything that moved the cash
--
-- SALE and REFUND are written by the system as bills are settled and returned.
-- PAY_IN, PAY_OUT, FLOAT and DROP are a human saying what they did, which is
-- why reason exists and why it matters more than the amount.
-- ---------------------------------------------------------------------------

CREATE TABLE cash_movement (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id   BIGINT         NOT NULL,
    type       VARCHAR(20)    NOT NULL,

    -- Always positive. The direction belongs to the type, for the same reason
    -- it does in stock_movement: a negative amount on a PAY_OUT would quietly
    -- put money in.
    amount     NUMERIC(12, 2) NOT NULL,

    reason     VARCHAR(500),
    ref_type   VARCHAR(30),
    ref_id     BIGINT,
    created_by VARCHAR(50)    NOT NULL,
    created_at TIMESTAMP      NOT NULL,

    CONSTRAINT fk_cash_mv_shift FOREIGN KEY (shift_id) REFERENCES cash_shift (id),
    CONSTRAINT ck_cash_mv_amount CHECK (amount >= 0),
    CONSTRAINT ck_cash_mv_type CHECK (type IN (
        'SALE',     -- a bill settled in cash
        'REFUND',   -- cash handed back (P7)
        'PAY_IN',   -- money put in for a reason that is not a sale
        'PAY_OUT',  -- money taken out: a supplier paid, a delivery tipped
        'FLOAT',    -- more change brought to the till
        'DROP'))    -- cash removed to the safe
);

CREATE INDEX ix_cash_mv_shift ON cash_movement (shift_id, created_at);
CREATE INDEX ix_cash_mv_ref   ON cash_movement (ref_type, ref_id);
