-- ---------------------------------------------------------------------------
-- V15 — who the bill belongs to
--
-- Every sale so far has been anonymous. A regular who eats here twice a week
-- is indistinguishable from someone passing through, which makes "who are our
-- regulars", "what does this table usually order" and any loyalty scheme at
-- all unanswerable.
--
-- docs/PLAN.md numbered this V12. That number went to sale_payment.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- The customer
--
-- No branch_id. ERD §3.4 has one and P1 has not landed, so there is no branch
-- table to point at; the code is unique on its own until there is. That is the
-- narrower constraint, so widening it later loses nothing.
--
-- Phone is indexed and deliberately not unique. It is the lookup key at the
-- till and it is also shared between a husband and wife, reassigned by the
-- carrier, and mistyped — a unique constraint on it turns a routine slip into
-- a blocked sale with a queue waiting.
-- ---------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS seq_customer_code
    START WITH 1 INCREMENT BY 1;

CREATE TABLE customer (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL,
    name       VARCHAR(150) NOT NULL,
    phone      VARCHAR(30),
    email      VARCHAR(120),
    birth_date DATE,
    note       VARCHAR(500),

    act_yn     VARCHAR(1)   NOT NULL DEFAULT 'Y',
    reg_id     VARCHAR(50),
    reg_dtm    TIMESTAMP,
    mod_id     VARCHAR(50),
    mod_dtm    TIMESTAMP,

    CONSTRAINT uk_customer_code UNIQUE (code)
);

CREATE INDEX ix_customer_phone ON customer (phone);
CREATE INDEX ix_customer_name  ON customer (name);

-- ---------------------------------------------------------------------------
-- The points ledger
--
-- There is no points_balance column, on purpose: a balance is the sum of the
-- ledger, and storing it as well means two numbers that can disagree with
-- nobody able to say which is right. The same argument as expected_cash in
-- V14 and balance_after in V11, except that here the sum is cheap enough that
-- not even a cache is needed.
--
-- points is signed, unlike stock_movement where the direction lives in the
-- type. Inconsistent, and ERD §3.4 says so plainly: stock's convention is
-- already established in a populated table and churning it would be a
-- migration for tidiness. New tables get signed amounts.
-- ---------------------------------------------------------------------------

CREATE TABLE loyalty_transaction (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT         NOT NULL,

    -- The bill that earned or spent them, when there was one. Null for a
    -- manual adjustment, which is the case the note exists for.
    order_id    BIGINT,

    type        VARCHAR(20)    NOT NULL,
    points      NUMERIC(12, 2) NOT NULL,
    note        VARCHAR(255),
    created_by  VARCHAR(50),
    created_at  TIMESTAMP      NOT NULL,

    CONSTRAINT fk_loyalty_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_loyalty_order    FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_loyalty_type CHECK (type IN (
        'EARN',      -- from a settled bill
        'REDEEM',    -- spent against one
        'ADJUST',    -- a manager putting it right
        'EXPIRE',    -- aged out
        'REVERSE'))  -- undone by a return (P7)
);

CREATE INDEX ix_loyalty_customer ON loyalty_transaction (customer_id, created_at);
CREATE INDEX ix_loyalty_order    ON loyalty_transaction (order_id);

-- One EARN row per bill at most. Without this a retried settlement, or a
-- second code path added later, can pay a customer twice for one meal — and
-- the ledger being the balance means the error is permanent.
CREATE UNIQUE INDEX ux_loyalty_earn_once
    ON loyalty_transaction (order_id, type);

-- ---------------------------------------------------------------------------
-- The bill learns who it belongs to
-- ---------------------------------------------------------------------------

ALTER TABLE orders ADD COLUMN customer_id BIGINT;

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customer (id);

CREATE INDEX ix_orders_customer ON orders (customer_id);

-- ---------------------------------------------------------------------------
-- What a dollar is worth
--
-- A setting rather than a constant, because it is a commercial decision that
-- will be changed by whoever owns the restaurant and not by whoever owns the
-- code. Zero turns earning off without removing the customer record.
-- ---------------------------------------------------------------------------

INSERT INTO app_setting (setting_key, setting_value, description, reg_id, reg_dtm) VALUES
    ('loyalty.pointsPerUsd', '1', 'Points earned per US dollar spent', 'system', CURRENT_TIMESTAMP),
    ('customer.codePrefix',  'C-', 'Prefix for generated customer codes',  'system', CURRENT_TIMESTAMP);
