-- ---------------------------------------------------------------------------
-- V16 — money going back
--
-- Until now a mistake could only be fixed by cancelling an unpaid bill. Once a
-- bill was settled there was nothing to undo it with: no way to put a dish back
-- on the shelf, take the cash out of the drawer, reverse the points or record
-- who agreed to any of it.
--
-- docs/PLAN.md numbered this V15. That number went to customers.
--
-- ---------------------------------------------------------------------------
-- A separate document, not negative rows on the original
--
-- ERD §3.7, and worth restating: the original sale is a printed record that
-- somebody may be holding. Editing it to show what was given back would mean
-- the receipt in their hand and the row in the database disagree, with no way
-- to tell which came first. A return points at the sale and leaves it alone.
--
-- ---------------------------------------------------------------------------
-- What the database cannot enforce
--
-- Returning 3 of a line of 2 across two documents needs a sum across every
-- return for that line, which no CHECK can express. ERD §3.7 names it so it
-- will not be forgotten: it is a service-layer check, and the endpoint
-- GET /orders/{id}/returnable exists so the client never has to do the
-- subtraction itself.
-- ---------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS seq_return_no
    START WITH 1 INCREMENT BY 1;

CREATE TABLE sale_return (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT         NOT NULL,
    return_no     VARCHAR(20)    NOT NULL,

    -- The drawer the money came out of. Null when nothing came out of one:
    -- a card refund does not touch the till.
    shift_id      BIGINT,

    -- Not nullable, and not defaulted. A refund with no reason is the entry
    -- nobody can account for at the end of the month.
    reason        VARCHAR(500)   NOT NULL,

    total         NUMERIC(12, 2) NOT NULL,
    refund_method VARCHAR(20)    NOT NULL,

    -- Who agreed to it, when agreement was required. SCREENS §3.4 asks for a
    -- threshold above which a manager signs: not because cashiers are
    -- dishonest, but because a refund needs a name against it and this is the
    -- cheapest place to capture one.
    approved_by   BIGINT,

    act_yn        VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id        VARCHAR(50),
    reg_dtm       TIMESTAMP,
    mod_id        VARCHAR(50),
    mod_dtm       TIMESTAMP,

    CONSTRAINT uk_return_no        UNIQUE (return_no),
    CONSTRAINT fk_return_order     FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_return_shift     FOREIGN KEY (shift_id) REFERENCES cash_shift (id),
    CONSTRAINT fk_return_approver  FOREIGN KEY (approved_by) REFERENCES users_infm (id),
    CONSTRAINT ck_return_total     CHECK (total > 0),
    CONSTRAINT ck_return_method    CHECK (refund_method IN ('CASH', 'CARD', 'KHQR', 'TRANSFER'))
);

CREATE INDEX ix_return_order ON sale_return (order_id);
CREATE INDEX ix_return_shift ON sale_return (shift_id);

CREATE TABLE sale_return_item (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id     BIGINT         NOT NULL,
    order_item_id BIGINT         NOT NULL,
    qty           NUMERIC(12, 2) NOT NULL,
    line_total    NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_return_item_return FOREIGN KEY (return_id) REFERENCES sale_return (id) ON DELETE CASCADE,
    CONSTRAINT fk_return_item_line   FOREIGN KEY (order_item_id) REFERENCES order_item (id),
    CONSTRAINT ck_return_item_qty    CHECK (qty > 0)
);

CREATE INDEX ix_return_item_return ON sale_return_item (return_id);
CREATE INDEX ix_return_item_line   ON sale_return_item (order_item_id);

-- ---------------------------------------------------------------------------
-- Fixing what V15's index forbade
--
-- V15 put a unique index on loyalty_transaction (order_id, type) to stop one
-- meal earning points twice. It also, unintentionally, stopped a bill being
-- returned twice: every return writes a REVERSE row against the order, so the
-- second partial refund on a bill hit the constraint and failed with a bare
-- 409. The tests did not catch it because they returned bills that had no
-- customer, and so wrote no REVERSE rows at all.
--
-- The rule that was wanted is about EARN alone. A partial index would say so
-- directly and is PostgreSQL-only, which V14 has already been through, so the
-- same portable shape is used here: a column that holds the order id for an
-- EARN row and NULL for everything else, under a plain UNIQUE. Many NULLs are
-- allowed on both engines, two equal values are not.
-- ---------------------------------------------------------------------------

ALTER TABLE loyalty_transaction ADD COLUMN earn_order_id BIGINT;

UPDATE loyalty_transaction SET earn_order_id = order_id WHERE type = 'EARN';

DROP INDEX ux_loyalty_earn_once;

CREATE UNIQUE INDEX ux_loyalty_earn_once ON loyalty_transaction (earn_order_id);

-- ---------------------------------------------------------------------------
-- The key cannot drift from the row it describes
--
-- Note the explicit IS NOT NULL, which the obvious version of this constraint
-- leaves out:
--
--     CHECK ((type = 'EARN' AND earn_order_id = order_id) OR ...)
--
-- An EARN row with a null key makes that read `NULL = order_id`, which is
-- unknown rather than false, and a CHECK only rejects what evaluates to
-- false. So the one row the constraint exists to forbid -- an EARN with no
-- key, which the unique index can never catch -- would have passed straight
-- through it.
-- ---------------------------------------------------------------------------

ALTER TABLE loyalty_transaction
    ADD CONSTRAINT ck_loyalty_earn_key CHECK (
        (type = 'EARN'  AND earn_order_id IS NOT NULL AND earn_order_id = order_id)
     OR (type <> 'EARN' AND earn_order_id IS NULL));

-- ---------------------------------------------------------------------------
-- And the same hole in V14
--
-- ck_shift_open_key was written the same way and has the same gap: a shift
-- saved OPEN with a null open_user_ref evaluates to unknown, passes, and
-- escapes the one-open-shift rule entirely -- the rule that constraint exists
-- to carry.
--
-- CashShift.open() and close() move the three facts together so the
-- application cannot produce such a row, which is why nothing has gone wrong.
-- But a constraint that depends on the application being careful is not a
-- constraint, and V14 cannot be edited now that it has been applied.
-- ---------------------------------------------------------------------------

ALTER TABLE cash_shift DROP CONSTRAINT ck_shift_open_key;

ALTER TABLE cash_shift
    ADD CONSTRAINT ck_shift_open_key CHECK (
        (status = 'OPEN'
            AND open_user_ref IS NOT NULL
            AND open_user_ref = user_ref
            AND closed_at IS NULL
            AND declared_cash IS NULL)
     OR (status = 'CLOSED'
            AND open_user_ref IS NULL
            AND closed_at IS NOT NULL
            AND declared_cash IS NOT NULL));

-- ---------------------------------------------------------------------------
-- When a manager has to agree
--
-- A setting, because the number is a judgement about this restaurant and not
-- about this software. Zero means every refund needs approval; a very large
-- number means none do, which is a decision somebody can make rather than a
-- behaviour they have to discover.
-- ---------------------------------------------------------------------------

INSERT INTO app_setting (setting_key, setting_value, description, reg_id, reg_dtm) VALUES
    ('returns.approvalThreshold', '20', 'Refunds above this need a manager', 'system', CURRENT_TIMESTAMP),
    ('sales.returnPrefix', 'RET-', 'Prefix for generated return numbers', 'system', CURRENT_TIMESTAMP);
