-- ---------------------------------------------------------------------------
-- V17 — one shop becomes one of several
--
-- Nothing in this schema has ever said which restaurant a row belongs to,
-- because there has only ever been one. The moment there are two, every table
-- without that column holds rows belonging to nobody in particular, and every
-- query returns both shops' business to whoever asked first.
--
-- docs/PLAN.md numbered this V6 and V7 and said to do it first. It is being
-- done last instead, which is the most expensive order available: there are
-- now 192 settled bills, a stock ledger, two shifts' worth of cash movements
-- and a customer ledger to carry across rather than a handful of rows. The
-- argument for doing it first was exactly this, and it was right.
--
-- ---------------------------------------------------------------------------
-- NOT NULL from the start
--
-- ERD §3.1: a nullable tenant key becomes a permanent source of rows belonging
-- to nobody. Every column below is added, backfilled to branch 1 and made NOT
-- NULL in the same migration, so there is never a moment when a row can be
-- written without a branch.
--
-- ---------------------------------------------------------------------------
-- Branch implies company
--
-- company_id is not repeated on every table. Carrying both is denormalisation
-- that drifts; the join through branch is one hop and always correct.
-- ---------------------------------------------------------------------------

CREATE TABLE company (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(150) NOT NULL,
    name_en VARCHAR(150),
    tax_id  VARCHAR(50),

    act_yn  VARCHAR(1)   NOT NULL DEFAULT 'Y',
    reg_id  VARCHAR(50),
    reg_dtm TIMESTAMP,
    mod_id  VARCHAR(50),
    mod_dtm TIMESTAMP
);

CREATE TABLE branch (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    code       VARCHAR(20)  NOT NULL,
    name       VARCHAR(150) NOT NULL,
    name_en    VARCHAR(150),
    address    VARCHAR(500),
    phone      VARCHAR(30),

    act_yn     VARCHAR(1)   NOT NULL DEFAULT 'Y',
    reg_id     VARCHAR(50),
    reg_dtm    TIMESTAMP,
    mod_id     VARCHAR(50),
    mod_dtm    TIMESTAMP,

    CONSTRAINT fk_branch_company FOREIGN KEY (company_id) REFERENCES company (id),
    CONSTRAINT uk_branch_code    UNIQUE (company_id, code)
);

-- ---------------------------------------------------------------------------
-- The shop that already exists
--
-- Named from the settings the receipt already prints, so the branch badge says
-- what the slips say rather than "Branch 1". COALESCE because a missing
-- setting must not stop the migration.
-- ---------------------------------------------------------------------------

INSERT INTO company (id, name, name_en, reg_id, reg_dtm)
SELECT 1,
       COALESCE((SELECT setting_value FROM app_setting WHERE setting_key = 'restaurant.name'), 'Restaurant'),
       COALESCE((SELECT setting_value FROM app_setting WHERE setting_key = 'restaurant.nameEn'), 'Restaurant'),
       'system', CURRENT_TIMESTAMP;

INSERT INTO branch (id, company_id, code, name, name_en, address, phone, reg_id, reg_dtm)
SELECT 1, 1, 'MAIN',
       COALESCE((SELECT setting_value FROM app_setting WHERE setting_key = 'restaurant.name'), 'Restaurant'),
       COALESCE((SELECT setting_value FROM app_setting WHERE setting_key = 'restaurant.nameEn'), 'Restaurant'),
       (SELECT setting_value FROM app_setting WHERE setting_key = 'restaurant.address'),
       (SELECT setting_value FROM app_setting WHERE setting_key = 'restaurant.phone'),
       'system', CURRENT_TIMESTAMP;

-- Identity columns were handed explicit values above, so the generators have
-- to be told where to carry on from.
ALTER TABLE company ALTER COLUMN id RESTART WITH 2;
ALTER TABLE branch  ALTER COLUMN id RESTART WITH 2;

-- ---------------------------------------------------------------------------
-- The nine tables of ERD §3.1, and sale_return
--
-- Child rows are not given a branch of their own: order_item, sale_payment,
-- purchase_item, cash_movement, loyalty_transaction and sale_return_item are
-- only ever reached through a parent that has one. A second copy of the answer
-- is a second thing to keep in step.
--
-- category, supplier, staff, app_setting, fx_rate, audit_log and
-- idempotency_key stay unscoped, which is ERD §3.1's list taken at its word. A
-- shared menu structure and a shared supplier list are the normal arrangement
-- for one company's shops; when that stops being true it is a migration, not a
-- surprise.
-- ---------------------------------------------------------------------------

ALTER TABLE users_infm     ADD COLUMN branch_id BIGINT;
ALTER TABLE dining_table   ADD COLUMN branch_id BIGINT;
ALTER TABLE product        ADD COLUMN branch_id BIGINT;
ALTER TABLE stock_item     ADD COLUMN branch_id BIGINT;
ALTER TABLE stock_movement ADD COLUMN branch_id BIGINT;
ALTER TABLE purchase       ADD COLUMN branch_id BIGINT;
ALTER TABLE orders         ADD COLUMN branch_id BIGINT;
ALTER TABLE cash_shift     ADD COLUMN branch_id BIGINT;
ALTER TABLE customer       ADD COLUMN branch_id BIGINT;
ALTER TABLE sale_return    ADD COLUMN branch_id BIGINT;

UPDATE users_infm     SET branch_id = 1;
UPDATE dining_table   SET branch_id = 1;
UPDATE product        SET branch_id = 1;
UPDATE stock_item     SET branch_id = 1;
UPDATE stock_movement SET branch_id = 1;
UPDATE purchase       SET branch_id = 1;
UPDATE orders         SET branch_id = 1;
UPDATE cash_shift     SET branch_id = 1;
UPDATE customer       SET branch_id = 1;
UPDATE sale_return    SET branch_id = 1;

ALTER TABLE users_infm     ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE dining_table   ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE product        ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE stock_item     ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE stock_movement ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE purchase       ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE orders         ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE cash_shift     ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE customer       ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE sale_return    ALTER COLUMN branch_id SET NOT NULL;

ALTER TABLE users_infm     ADD CONSTRAINT fk_users_branch    FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE dining_table   ADD CONSTRAINT fk_table_branch    FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE product        ADD CONSTRAINT fk_product_branch  FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE stock_item     ADD CONSTRAINT fk_item_branch     FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE stock_movement ADD CONSTRAINT fk_movement_branch FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE purchase       ADD CONSTRAINT fk_purchase_branch FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE orders         ADD CONSTRAINT fk_orders_branch   FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE cash_shift     ADD CONSTRAINT fk_shift_branch    FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE customer       ADD CONSTRAINT fk_customer_branch FOREIGN KEY (branch_id) REFERENCES branch (id);
ALTER TABLE sale_return    ADD CONSTRAINT fk_return_branch   FOREIGN KEY (branch_id) REFERENCES branch (id);

-- Every scoped query begins with the branch, so every scoped index should too.
CREATE INDEX ix_table_branch    ON dining_table (branch_id);
CREATE INDEX ix_product_branch  ON product (branch_id);
CREATE INDEX ix_item_branch     ON stock_item (branch_id);
CREATE INDEX ix_movement_branch ON stock_movement (branch_id);
CREATE INDEX ix_purchase_branch ON purchase (branch_id);
CREATE INDEX ix_orders_branch   ON orders (branch_id, reg_dtm);
CREATE INDEX ix_shift_branch    ON cash_shift (branch_id);
CREATE INDEX ix_customer_branch ON customer (branch_id);

-- ---------------------------------------------------------------------------
-- Uniqueness becomes per-branch
--
-- Two shops each have a Table 01 and each have their own customer codes. A
-- constraint that spans the company would make the second branch's first
-- working day an argument with the database.
--
-- Invoice and return numbers stay unique across the company: they are drawn
-- from one sequence and a tax authority asking about INV-00231 should get one
-- answer.
-- ---------------------------------------------------------------------------

ALTER TABLE customer DROP CONSTRAINT uk_customer_code;
ALTER TABLE customer ADD CONSTRAINT uk_customer_code UNIQUE (branch_id, code);

-- ---------------------------------------------------------------------------
-- One open shift per cashier per branch
--
-- V14's key held the cashier's id; with branches it has to say which till, or
-- a cashier covering two shops could only ever open one drawer. The CHECK is
-- carried over unchanged in substance, including V16's explicit nullness.
-- ---------------------------------------------------------------------------

ALTER TABLE cash_shift DROP CONSTRAINT ck_shift_open_key;
ALTER TABLE cash_shift DROP CONSTRAINT uk_shift_one_open;

ALTER TABLE cash_shift ADD COLUMN open_branch_id BIGINT;
UPDATE cash_shift SET open_branch_id = branch_id WHERE status = 'OPEN';

ALTER TABLE cash_shift
    ADD CONSTRAINT uk_shift_one_open UNIQUE (open_branch_id, open_user_ref);

ALTER TABLE cash_shift
    ADD CONSTRAINT ck_shift_open_key CHECK (
        (status = 'OPEN'
            AND open_user_ref IS NOT NULL
            AND open_user_ref = user_ref
            AND open_branch_id IS NOT NULL
            AND open_branch_id = branch_id
            AND closed_at IS NULL
            AND declared_cash IS NULL)
     OR (status = 'CLOSED'
            AND open_user_ref IS NULL
            AND open_branch_id IS NULL
            AND closed_at IS NOT NULL
            AND declared_cash IS NOT NULL));

-- ---------------------------------------------------------------------------
-- MANAGER
--
-- Referenced by @PreAuthorize on the shift and customer endpoints since P3 and
-- P6, and refused by the database until now, so the role existed in the
-- application's vocabulary and nowhere else.
-- ---------------------------------------------------------------------------

ALTER TABLE users_infm DROP CONSTRAINT ck_users_role;
ALTER TABLE users_infm ADD CONSTRAINT ck_users_role
    CHECK (role IN ('ADMIN', 'MANAGER', 'CASHIER', 'WAITER', 'CHEF'));

ALTER TABLE staff DROP CONSTRAINT ck_staff_role;
ALTER TABLE staff ADD CONSTRAINT ck_staff_role
    CHECK (role IN ('ADMIN', 'MANAGER', 'CASHIER', 'WAITER', 'CHEF'));
