-- ---------------------------------------------------------------------------
-- V18 — sizes, and the things people ask for
--
-- ARCHITECTURE §1.2 separates two ideas the brief ran together:
--
--   A **variant** is a distinct sellable thing. A large coffee has its own
--   price, its own cost and its own barcode; it is a different row on the
--   menu that happens to share a name with the small one.
--
--   A **modifier** is a property of one line. "No ice", "extra spicy",
--   "takeaway box" change what arrives and sometimes what it costs, but they
--   are not things anybody stocks.
--
-- Expressing the second as the first is the mistake this schema is shaped to
-- avoid: four sizes times no-ice times extra-spicy times takeaway is
-- thirty-two menu rows for one coffee, and somebody has to price all of them.
--
-- docs/PLAN.md numbered this V13.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Variants
--
-- No branch_id. A variant belongs to a product and a product belongs to a
-- branch, so the scope is one join away and a second copy would be a second
-- thing to keep in step (V17 took the same line with every other child table).
-- Reaching a variant without its product is what the service refuses.
-- ---------------------------------------------------------------------------

CREATE TABLE product_variant (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT         NOT NULL,

    sku        VARCHAR(50),
    -- Kept, and expected to be empty for food. ARCHITECTURE §1.3: packaged
    -- drinks have barcodes and dishes do not, which is why the POS search is
    -- name-first and a scanner is just another way of typing into it.
    barcode    VARCHAR(50),

    name       VARCHAR(100)   NOT NULL,
    name_en    VARCHAR(100),
    price      NUMERIC(12, 2) NOT NULL,
    cost       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sort_order INTEGER        NOT NULL DEFAULT 0,

    act_yn     VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id     VARCHAR(50),
    reg_dtm    TIMESTAMP,
    mod_id     VARCHAR(50),
    mod_dtm    TIMESTAMP,

    CONSTRAINT fk_variant_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT ck_variant_price   CHECK (price >= 0),
    CONSTRAINT ck_variant_cost    CHECK (cost >= 0)
);

CREATE INDEX ix_variant_product ON product_variant (product_id, sort_order);
CREATE INDEX ix_variant_barcode ON product_variant (barcode);

-- ---------------------------------------------------------------------------
-- Modifiers
--
-- Groups are shared across the menu rather than owned by one dish: "Sugar
-- level" is one question whoever is asking it, and attaching it to six drinks
-- should not mean six copies to keep in step. product_modifier_group is what
-- says which dishes ask which questions.
--
-- min_select and max_select are the question's shape. 0..1 is "would you like
-- anything", 1..1 is "you must choose one", 0..n is "tick what you want". The
-- CHECK below keeps the pair meaning something.
-- ---------------------------------------------------------------------------

CREATE TABLE modifier_group (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    name_en    VARCHAR(100),
    min_select INTEGER      NOT NULL DEFAULT 0,
    max_select INTEGER      NOT NULL DEFAULT 1,
    sort_order INTEGER      NOT NULL DEFAULT 0,

    act_yn     VARCHAR(1)   NOT NULL DEFAULT 'Y',
    reg_id     VARCHAR(50),
    reg_dtm    TIMESTAMP,
    mod_id     VARCHAR(50),
    mod_dtm    TIMESTAMP,

    CONSTRAINT ck_modifier_group_select CHECK (min_select >= 0 AND max_select >= min_select AND max_select > 0)
);

CREATE TABLE modifier (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT         NOT NULL,
    name        VARCHAR(100)   NOT NULL,
    name_en     VARCHAR(100),

    -- Signed on purpose: "no ice" is free, "extra shot" costs, and a discount
    -- for leaving something out is a real thing a restaurant does.
    price_delta NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sort_order  INTEGER        NOT NULL DEFAULT 0,

    act_yn      VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id      VARCHAR(50),
    reg_dtm     TIMESTAMP,
    mod_id      VARCHAR(50),
    mod_dtm     TIMESTAMP,

    CONSTRAINT fk_modifier_group FOREIGN KEY (group_id) REFERENCES modifier_group (id) ON DELETE CASCADE
);

CREATE INDEX ix_modifier_group ON modifier (group_id, sort_order);

CREATE TABLE product_modifier_group (
    product_id BIGINT NOT NULL,
    group_id   BIGINT NOT NULL,

    PRIMARY KEY (product_id, group_id),
    CONSTRAINT fk_pmg_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_pmg_group   FOREIGN KEY (group_id) REFERENCES modifier_group (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- What was actually ordered
--
-- modifier_name and price_delta are copied onto the line, for the same reason
-- product_name and unit_price already are: a receipt must stay true after a
-- rename or a reprice. modifier_id is nullable so deleting a modifier from the
-- menu does not destroy the history of what people ordered.
-- ---------------------------------------------------------------------------

CREATE TABLE order_item_modifier (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT         NOT NULL,
    modifier_id   BIGINT,
    modifier_name VARCHAR(100)   NOT NULL,
    price_delta   NUMERIC(12, 2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_oim_item     FOREIGN KEY (order_item_id) REFERENCES order_item (id) ON DELETE CASCADE,
    CONSTRAINT fk_oim_modifier FOREIGN KEY (modifier_id) REFERENCES modifier (id)
);

CREATE INDEX ix_oim_item ON order_item_modifier (order_item_id);

-- ---------------------------------------------------------------------------
-- The line remembers which variant it sold
--
-- unit_price already records what was charged, so the figure is safe. What was
-- missing is which of a product's sizes it was: without it a receipt reprint
-- says "Coffee" for a large one, and a sales report cannot tell the two apart.
-- The name is copied beside the id on the same argument as every other
-- denormalised name here.
-- ---------------------------------------------------------------------------

ALTER TABLE order_item ADD COLUMN variant_id   BIGINT;
ALTER TABLE order_item ADD COLUMN variant_name VARCHAR(100);

ALTER TABLE order_item
    ADD CONSTRAINT fk_order_item_variant FOREIGN KEY (variant_id) REFERENCES product_variant (id);
