-- ---------------------------------------------------------------------------
-- V19 — money off, by a rule rather than by hand
--
-- A manager has always been able to type a discount into the payment panel.
-- What there has been no way to express is "ten percent off drinks on a
-- Tuesday afternoon" — a rule that applies itself, the same way, to everybody
-- who qualifies, and that a report can later separate from the discounts
-- somebody gave out one at a time.
--
-- docs/PLAN.md numbered this V14.
--
-- ---------------------------------------------------------------------------
-- Percent and fixed only
--
-- SCREENS §3.5 says to ship those two first: buy-X-get-Y interacts with
-- returns, loyalty and tax in ways that are not obvious, and a wrong discount
-- is a wrong price on a printed receipt. BUY_X_GET_Y is in the CHECK anyway so
-- that adding it later is code rather than another migration — ERD §3.5 makes
-- the same point.
-- ---------------------------------------------------------------------------

CREATE TABLE promotion (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id  BIGINT         NOT NULL,

    name       VARCHAR(150)   NOT NULL,
    type       VARCHAR(20)    NOT NULL,

    -- A percentage for PERCENT, an amount of money for AMOUNT. One column
    -- because it is one idea — how much comes off — and two would mean every
    -- read checking which of them to look at.
    --
    -- ERD §3.5 calls it `value`, which H2 refuses: it is a reserved word
    -- there, and the migration would not parse. Quoting it would work and
    -- would put quotes around it in every query that ever touches it; the
    -- longer name costs nothing and reads better anyway.
    discount_value NUMERIC(12, 2) NOT NULL,

    scope      VARCHAR(20)    NOT NULL,
    -- The product for ITEM, the category for CATEGORY, null for ORDER.
    scope_id   BIGINT,

    -- Below this the rule does not apply. Null means no floor.
    min_amount NUMERIC(12, 2),

    starts_at  TIMESTAMP      NOT NULL,
    ends_at    TIMESTAMP      NOT NULL,

    -- Happy hour. Null means all day; a window that wraps midnight is read as
    -- two halves by the service rather than being forbidden here.
    time_from  TIME,
    time_to    TIME,

    act_yn     VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id     VARCHAR(50),
    reg_dtm    TIMESTAMP,
    mod_id     VARCHAR(50),
    mod_dtm    TIMESTAMP,

    CONSTRAINT fk_promo_branch FOREIGN KEY (branch_id) REFERENCES branch (id),
    CONSTRAINT ck_promo_type   CHECK (type IN ('PERCENT', 'AMOUNT', 'BUY_X_GET_Y')),
    CONSTRAINT ck_promo_scope  CHECK (scope IN ('ITEM', 'CATEGORY', 'ORDER')),
    CONSTRAINT ck_promo_dates  CHECK (ends_at > starts_at),
    CONSTRAINT ck_promo_value  CHECK (discount_value > 0),

    -- A scope that names nothing, or an ORDER rule that names something, is a
    -- rule nobody can apply. The CHECK says which combinations mean anything.
    CONSTRAINT ck_promo_scope_id CHECK (
        (scope = 'ORDER' AND scope_id IS NULL)
     OR (scope IN ('ITEM', 'CATEGORY') AND scope_id IS NOT NULL))
);

CREATE INDEX ix_promo_branch ON promotion (branch_id, act_yn);
CREATE INDEX ix_promo_window ON promotion (starts_at, ends_at);

-- ---------------------------------------------------------------------------
-- What a bill actually got
--
-- Recorded on the bill, not recomputed from the rules when somebody asks.
-- A promotion can be edited or deleted next week, and a receipt in somebody's
-- hand says what it says — the same argument that put unit_price on the line
-- and fx_rate_khr on the order.
--
-- promo_discount is kept apart from the existing discount column on purpose.
-- "The manager took five dollars off" and "Tuesday's rule took five dollars
-- off" are different facts, and a report that cannot tell them apart cannot
-- answer whether the rule is worth running.
-- ---------------------------------------------------------------------------

ALTER TABLE orders ADD COLUMN promo_discount NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN promotion_id   BIGINT;

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id);

ALTER TABLE order_item ADD COLUMN discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE order_item ADD COLUMN promotion_id    BIGINT;

ALTER TABLE order_item
    ADD CONSTRAINT fk_order_item_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id);

CREATE INDEX ix_order_item_promo ON order_item (promotion_id);
