-- ---------------------------------------------------------------------------
-- V2 — core schema
--
-- Written in portable DDL (identity columns, NUMERIC, CHECK) so the same
-- migrations run on PostgreSQL and on H2 in PostgreSQL mode, which is what the
-- `dev` profile uses. Avoid PostgreSQL-only syntax here.
--
-- Money is NUMERIC(12,2) throughout. Riel totals are NUMERIC(14,0) — the riel
-- has no minor unit.
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- Users & authentication
-- ===========================================================================

CREATE TABLE users_infm (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_key          VARCHAR(10)  NOT NULL,
    user_id          VARCHAR(50)  NOT NULL,
    user_nm          VARCHAR(100) NOT NULL,
    user_pwd         VARCHAR(255) NOT NULL,
    tel              VARCHAR(30),
    eml              VARCHAR(120),
    usr_img          VARCHAR(255),
    role             VARCHAR(20)  NOT NULL,
    lock_yn          VARCHAR(1)   NOT NULL DEFAULT 'N',
    login_failed_cnt INTEGER      NOT NULL DEFAULT 0,
    lst_lgn_dtm      TIMESTAMP,
    act_yn           VARCHAR(1)   NOT NULL DEFAULT 'Y',
    reg_id           VARCHAR(50),
    reg_dtm          TIMESTAMP,
    mod_id           VARCHAR(50),
    mod_dtm          TIMESTAMP,
    CONSTRAINT uk_users_biz_key UNIQUE (biz_key),
    CONSTRAINT uk_users_user_id UNIQUE (user_id),
    CONSTRAINT ck_users_role    CHECK (role IN ('ADMIN', 'CASHIER', 'WAITER', 'CHEF'))
);

CREATE TABLE password_reset_token (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL,
    otp_code   VARCHAR(10),
    user_ref   BIGINT       NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    used_yn    VARCHAR(1)   NOT NULL DEFAULT 'N',
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_prt_token UNIQUE (token),
    CONSTRAINT fk_prt_user  FOREIGN KEY (user_ref) REFERENCES users_infm (id) ON DELETE CASCADE
);

CREATE INDEX ix_prt_user ON password_reset_token (user_ref);

-- ===========================================================================
-- Staff
-- ===========================================================================

CREATE TABLE staff (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_code    VARCHAR(20)  NOT NULL,
    staff_name    VARCHAR(100) NOT NULL,
    gender        VARCHAR(10),
    date_of_birth DATE,
    phone         VARCHAR(30),
    email         VARCHAR(120),
    role          VARCHAR(20)  NOT NULL,
    shift         VARCHAR(20),
    salary        NUMERIC(12, 2),
    hire_date     DATE,
    address       VARCHAR(500),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    user_ref      BIGINT,
    act_yn        VARCHAR(1)   NOT NULL DEFAULT 'Y',
    reg_id        VARCHAR(50),
    reg_dtm       TIMESTAMP,
    mod_id        VARCHAR(50),
    mod_dtm       TIMESTAMP,
    CONSTRAINT uk_staff_code   UNIQUE (staff_code),
    CONSTRAINT fk_staff_user   FOREIGN KEY (user_ref) REFERENCES users_infm (id) ON DELETE SET NULL,
    CONSTRAINT ck_staff_role   CHECK (role IN ('ADMIN', 'CASHIER', 'WAITER', 'CHEF')),
    CONSTRAINT ck_staff_status CHECK (status IN ('ACTIVE', 'ON_LEAVE', 'RESIGNED')),
    CONSTRAINT ck_staff_shift  CHECK (shift IS NULL OR shift IN ('MORNING', 'EVENING', 'FULL_TIME'))
);

-- ===========================================================================
-- Catalog
-- ===========================================================================

CREATE TABLE category (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    name_en    VARCHAR(100),
    icon       VARCHAR(20),
    sort_order INTEGER      NOT NULL DEFAULT 0,
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    act_yn     VARCHAR(1)   NOT NULL DEFAULT 'Y',
    reg_id     VARCHAR(50),
    reg_dtm    TIMESTAMP,
    mod_id     VARCHAR(50),
    mod_dtm    TIMESTAMP,
    CONSTRAINT ck_category_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE product (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150)   NOT NULL,
    name_en     VARCHAR(150),
    category_id BIGINT         NOT NULL,
    price       NUMERIC(12, 2) NOT NULL,
    cost        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock_qty   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    image_url   VARCHAR(255),
    description VARCHAR(1000),
    status      VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    act_yn      VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id      VARCHAR(50),
    reg_dtm     TIMESTAMP,
    mod_id      VARCHAR(50),
    mod_dtm     TIMESTAMP,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT ck_product_status   CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_product_price    CHECK (price >= 0),
    CONSTRAINT ck_product_cost     CHECK (cost >= 0)
);

CREATE INDEX ix_product_category ON product (category_id);

-- ===========================================================================
-- Dining tables
-- ===========================================================================

CREATE TABLE dining_table (
    id      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) NOT NULL,
    seats   INTEGER     NOT NULL,
    zone    VARCHAR(20) NOT NULL DEFAULT 'INDOOR',
    status  VARCHAR(20) NOT NULL DEFAULT 'FREE',
    act_yn  VARCHAR(1)  NOT NULL DEFAULT 'Y',
    reg_id  VARCHAR(50),
    reg_dtm TIMESTAMP,
    mod_id  VARCHAR(50),
    mod_dtm TIMESTAMP,
    CONSTRAINT uk_dining_table_name UNIQUE (name),
    CONSTRAINT ck_dining_zone       CHECK (zone IN ('INDOOR', 'OUTDOOR', 'VIP')),
    CONSTRAINT ck_dining_status     CHECK (status IN ('FREE', 'OCCUPIED', 'RESERVED')),
    CONSTRAINT ck_dining_seats      CHECK (seats > 0)
);

-- ===========================================================================
-- Orders
-- ===========================================================================

CREATE TABLE orders (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no      VARCHAR(20)    NOT NULL,
    table_id        BIGINT,
    cashier_id      BIGINT,
    guest_count     INTEGER,
    subtotal        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    vat_rate        NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    vat_amount      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total           NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_khr       NUMERIC(14, 0) NOT NULL DEFAULT 0,
    payment_method  VARCHAR(20),
    amount_tendered NUMERIC(12, 2),
    change_amount   NUMERIC(12, 2),
    status          VARCHAR(20)    NOT NULL DEFAULT 'OPEN',
    paid_at         TIMESTAMP,
    act_yn          VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id          VARCHAR(50),
    reg_dtm         TIMESTAMP,
    mod_id          VARCHAR(50),
    mod_dtm         TIMESTAMP,
    CONSTRAINT uk_orders_invoice_no UNIQUE (invoice_no),
    CONSTRAINT fk_orders_table      FOREIGN KEY (table_id) REFERENCES dining_table (id),
    CONSTRAINT fk_orders_cashier    FOREIGN KEY (cashier_id) REFERENCES users_infm (id),
    CONSTRAINT ck_orders_status     CHECK (status IN ('OPEN', 'PAID', 'CANCELLED')),
    CONSTRAINT ck_orders_payment    CHECK (payment_method IS NULL
                                           OR payment_method IN ('CASH', 'CARD', 'KHQR', 'TRANSFER'))
);

CREATE INDEX ix_orders_status  ON orders (status);
CREATE INDEX ix_orders_reg_dtm ON orders (reg_dtm);
CREATE INDEX ix_orders_table   ON orders (table_id);

-- product_name is denormalised on purpose: a printed receipt must stay correct
-- after the product is renamed or removed from the catalog.
CREATE TABLE order_item (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL,
    product_id   BIGINT,
    product_name VARCHAR(150)   NOT NULL,
    qty          NUMERIC(12, 2) NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    line_total   NUMERIC(12, 2) NOT NULL,
    note         VARCHAR(255),
    CONSTRAINT fk_order_item_order   FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT ck_order_item_qty     CHECK (qty > 0)
);

CREATE INDEX ix_order_item_order ON order_item (order_id);

-- ===========================================================================
-- Suppliers & purchasing
-- ===========================================================================

CREATE TABLE supplier (
    id             BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code  VARCHAR(20)    NOT NULL,
    company        VARCHAR(150)   NOT NULL,
    contact_person VARCHAR(100),
    phone          VARCHAR(30),
    email          VARCHAR(120),
    supply_type    VARCHAR(30),
    address        VARCHAR(500),
    balance        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status         VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    act_yn         VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id         VARCHAR(50),
    reg_dtm        TIMESTAMP,
    mod_id         VARCHAR(50),
    mod_dtm        TIMESTAMP,
    CONSTRAINT uk_supplier_code   UNIQUE (supplier_code),
    CONSTRAINT ck_supplier_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE stock_item (
    id        BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(150)   NOT NULL,
    unit      VARCHAR(30)    NOT NULL,
    qty       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    min_qty   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    unit_cost NUMERIC(12, 2) NOT NULL DEFAULT 0,
    act_yn    VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id    VARCHAR(50),
    reg_dtm   TIMESTAMP,
    mod_id    VARCHAR(50),
    mod_dtm   TIMESTAMP,
    CONSTRAINT ck_stock_item_qty     CHECK (qty >= 0),
    CONSTRAINT ck_stock_item_min_qty CHECK (min_qty >= 0)
);

CREATE TABLE purchase (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no         VARCHAR(20)    NOT NULL,
    supplier_id   BIGINT         NOT NULL,
    purchase_date DATE           NOT NULL,
    total         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status        VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    note          VARCHAR(500),
    act_yn        VARCHAR(1)     NOT NULL DEFAULT 'Y',
    reg_id        VARCHAR(50),
    reg_dtm       TIMESTAMP,
    mod_id        VARCHAR(50),
    mod_dtm       TIMESTAMP,
    CONSTRAINT uk_purchase_po_no  UNIQUE (po_no),
    CONSTRAINT fk_purchase_supp   FOREIGN KEY (supplier_id) REFERENCES supplier (id),
    CONSTRAINT ck_purchase_status CHECK (status IN ('PENDING', 'RECEIVED', 'CANCELLED'))
);

CREATE INDEX ix_purchase_supplier ON purchase (supplier_id);
CREATE INDEX ix_purchase_date     ON purchase (purchase_date);

CREATE TABLE purchase_item (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id   BIGINT         NOT NULL,
    stock_item_id BIGINT         NOT NULL,
    item_name     VARCHAR(150)   NOT NULL,
    qty           NUMERIC(12, 2) NOT NULL,
    unit_cost     NUMERIC(12, 2) NOT NULL,
    line_total    NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_pitem_purchase FOREIGN KEY (purchase_id) REFERENCES purchase (id) ON DELETE CASCADE,
    CONSTRAINT fk_pitem_stock    FOREIGN KEY (stock_item_id) REFERENCES stock_item (id),
    CONSTRAINT ck_pitem_qty      CHECK (qty > 0)
);

CREATE INDEX ix_pitem_purchase ON purchase_item (purchase_id);

CREATE TABLE stock_movement (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_item_id BIGINT         NOT NULL,
    movement_type VARCHAR(20)    NOT NULL,
    qty           NUMERIC(12, 2) NOT NULL,
    reason        VARCHAR(500),
    created_by    VARCHAR(50),
    created_at    TIMESTAMP      NOT NULL,
    CONSTRAINT fk_movement_stock FOREIGN KEY (stock_item_id) REFERENCES stock_item (id),
    CONSTRAINT ck_movement_type  CHECK (movement_type IN ('IN', 'OUT', 'DAMAGED')),
    CONSTRAINT ck_movement_qty   CHECK (qty > 0)
);

CREATE INDEX ix_movement_stock ON stock_movement (stock_item_id);
CREATE INDEX ix_movement_date  ON stock_movement (created_at);

-- ===========================================================================
-- Settings
-- ===========================================================================

CREATE TABLE app_setting (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key   VARCHAR(100) NOT NULL,
    setting_value VARCHAR(1000),
    description   VARCHAR(255),
    act_yn        VARCHAR(1)   NOT NULL DEFAULT 'Y',
    reg_id        VARCHAR(50),
    reg_dtm       TIMESTAMP,
    mod_id        VARCHAR(50),
    mod_dtm       TIMESTAMP,
    CONSTRAINT uk_app_setting_key UNIQUE (setting_key)
);
