-- ---------------------------------------------------------------------------
-- V6 — idempotency keys
--
-- A cashier on bad Wi-Fi taps "Pay" twice and the second tap must not create a
-- second bill. The unique constraint below is the entire mechanism: the second
-- request loses the insert, finds the first request's stored response, and
-- returns it.
--
-- Numbered V6 rather than the V11 in docs/ERD.md because the build order in
-- docs/PLAN.md puts this before multi-branch. The document's numbering was
-- illustrative; Flyway's is not.
--
-- response_body stores the finished JSON rather than the ERD's response_ref
-- pointing at a created row. A reference would need per-endpoint logic to
-- rebuild each reply, and would still not reproduce one exactly. Storing the
-- body replays it byte for byte and is indifferent to which endpoint it came
-- from.
-- ---------------------------------------------------------------------------

CREATE TABLE idempotency_key (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_value       VARCHAR(80)  NOT NULL,
    method          VARCHAR(10)  NOT NULL,
    path            VARCHAR(255) NOT NULL,
    state           VARCHAR(20)  NOT NULL DEFAULT 'IN_PROGRESS',
    response_status INTEGER,
    -- Large enough for an order with many lines. A reply that will not fit is
    -- not truncated: see IdempotencyService.complete, which records the
    -- attempt as unreplayable rather than storing JSON that cannot be parsed.
    response_body   VARCHAR(8000),
    user_id         VARCHAR(50),
    created_at      TIMESTAMP    NOT NULL,
    completed_at    TIMESTAMP,
    CONSTRAINT uk_idem_key   UNIQUE (key_value),
    CONSTRAINT ck_idem_state CHECK (state IN ('IN_PROGRESS', 'COMPLETED'))
);

-- Retention: nothing prunes this yet. At ~200 sales a day it grows by roughly
-- 70k rows a year, which is not a problem at this size but is not free either.
-- A scheduled delete of rows older than 24 hours belongs here once anything
-- depends on it — a key is only useful for as long as a client might retry.
CREATE INDEX ix_idem_created ON idempotency_key (created_at);
