-- ---------------------------------------------------------------------------
-- V7 — audit log
--
-- The reg_id / mod_id / reg_dtm / mod_dtm columns on every business table say
-- who touched a row last. They cannot say who changed a price, from what, to
-- what, or how many times — the previous value is gone the moment it is
-- overwritten. That is the question an audit log exists to answer.
--
-- Append-only. There is no update path and no delete endpoint: a log that can
-- be edited is not one. Rows are written by a Hibernate change listener rather
-- than by each service, because the failure mode of "remember to audit this"
-- is silence exactly where it matters.
--
-- Numbered V7 by build order, not by the V11 in docs/ERD.md — same reason as
-- V6.
-- ---------------------------------------------------------------------------

CREATE TABLE audit_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_ref    BIGINT,
    -- Copied as text as well as referenced, so the log still names someone
    -- after the account is deleted. A foreign key alone would leave the most
    -- interesting rows anonymous.
    user_id     VARCHAR(50)  NOT NULL,
    action      VARCHAR(20)  NOT NULL,
    entity      VARCHAR(50)  NOT NULL,
    entity_id   BIGINT,
    -- Only the fields that changed, not whole records: an update stores
    -- {"price":"3.50"} against {"price":"4.00"} rather than two copies of a
    -- product. Truncated with a marker if it will not fit, because a readable
    -- partial record beats a failed write on the audit path.
    before_json VARCHAR(4000),
    after_json  VARCHAR(4000),
    ip          VARCHAR(45),
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT ck_audit_action CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
    CONSTRAINT fk_audit_user   FOREIGN KEY (user_ref) REFERENCES users_infm (id) ON DELETE SET NULL
);

CREATE INDEX ix_audit_entity  ON audit_log (entity, entity_id);
CREATE INDEX ix_audit_created ON audit_log (created_at);
CREATE INDEX ix_audit_user    ON audit_log (user_id);
